// vue-app/src/containers/Home/index.vue
<template>
  <div>
    <img alt="Vue logo" src="../../assets/logo.png" />
    <p>Home Page</p>
  </div>
</template>

<script>
export default {
  name: 'App',
  created() {
    console.log('vue2.0写法 created');
  },
  mounted() {
    console.log(this.$route);
  },
  methods: {
    close() {
      console.log('close');
    },
  },
};
</script>

// react-app/src/containers/Home/index.js
import React, { memo } from 'react';
import LogoPng from '../../logo.svg';

function Home() {
  return (
    <div>
      <header className="App-header">
        <img style={{ width: 240, height: 240 }} src={LogoPng} alt="" />
        Home Page
      </header>
    </div>
  )
}

export default memo(Home);
